[build]
target = "thumbv7em-none-eabi"   # Cortex-M4 and Cortex-M7 (no FPU)
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Map=app.map",
]

[alias]
build-softdevice = "objcopy --release --bin softdevice -- softdevice.elf"
build-softdevice-bin = "objcopy --release --bin softdevice -- -O binary softdevice.bin"